packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: ^5.7.0
  eslint: ^10.3.0
  eslint-plugin-boundaries: ^6.0.2
  eslint-plugin-react-hooks: ^7.1.1
  eslint-import-resolver-typescript: ^4.4.4
  '@typescript-eslint/parser': ^8.59.1
  vitest: ^4.1.5
